branches:
    only:
      - /.*/

language:
    - rust
    - go

git:
    quiet: true

os:
    - linux
    - osx
    - windows

arch:
    - amd64
    - arm64

before_script:
    - env

script:
    - if [ "x$TRAVIS_LANGUAGE" = "xrust" ]; then
          (cd bindings/rust; cargo test)
      fi
    - if [ "x$TRAVIS_LANGUAGE" = "xgo" ]; then
          (cd bindings/go; go test -test.v)
      fi

notifications:
    email: false

before_cache:
    - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

cache:
    cargo: true
    directories:
      - bindings/rust/target

