branches:
    only:
      - /.*/

language: rust

git:
    quiet: true

os:
    - linux
    - osx
    - windows

arch:
    - amd64
    - arm64

before_script:
    - env

script:
    - if [ "x$TRAVIS_LANGUAGE" = "xrust" ]; then
          if [ "x$TRAVIS_OS_NAME" = "xwindows" ]; then
              rustup toolchain add stable-x86_64-pc-windows-msvc;
              rustup set default-host x86_64-pc-windows-msvc;
          fi;
          (cd bindings/rust; cargo test)
      fi
    - if which go > /dev/null; then
          (cd bindings/go; go test -test.v)
      fi

matrix:
    include:
      - os: linux
        arch: arm64
        language: go
      - os: windows
        language: go


notifications:
    email: false

before_cache:
    - rm -rf "$TRAVIS_HOME/.cargo/registry/src"

cache:
    cargo: true
    directories:
      - bindings/rust/target

